#!/usr/bin/env node

/**
 * generate.js — Single source of truth → output files
 *
 * Reads:   data/feature-flags.json
 * Writes:  feature-flags.md   (engineering reference)
 *          index.html          (clinical team viewer)
 *
 * Usage:   node generate.js
 */

const fs = require("fs");
const path = require("path");

// ─── Paths ────────────────────────────────────────────────────────────────────
const ROOT = __dirname;
const JSON_PATH = path.join(ROOT, "data", "feature-flags.json");
const MD_PATH = path.join(ROOT, "feature-flags.md");
const HTML_PATH = path.join(ROOT, "index.html");

// ─── Load data ────────────────────────────────────────────────────────────────
let data;
try {
  data = JSON.parse(fs.readFileSync(JSON_PATH, "utf-8"));
} catch (err) {
  console.error(`Error reading ${JSON_PATH}:`, err.message);
  process.exit(1);
}

// ═══════════════════════════════════════════════════════════════════════════════
//  MARKDOWN GENERATION
// ═══════════════════════════════════════════════════════════════════════════════

function generateMarkdown() {
  const lines = [];
  const ln = (s = "") => lines.push(s);

  // ── Header ──────────────────────────────────────────────────────────────────
  ln("# Feature Flags Reference");
  ln();
  ln(`> **Last updated:** ${data.meta.lastUpdated}`);
  ln(">");
  ln("> This document is auto-generated from `data/feature-flags.json`.");
  ln("> **Do not edit this file directly** — run `node generate.js` after updating the JSON.");
  ln();
  ln("---");
  ln();

  // ── Products ────────────────────────────────────────────────────────────────
  ln("## Products");
  ln();
  ln("| Product | Description |");
  ln("|---------|-------------|");
  for (const p of data.products) {
    ln(`| ${p.name} | ${p.description} |`);
  }
  ln();

  // ── Customers Overview ──────────────────────────────────────────────────────
  ln("## Customers Overview");
  ln();
  ln("| Customer | Products | EHR Platform |");
  ln("|----------|----------|--------------|");
  for (const c of data.customers) {
    const productNames = c.products
      .map((pk) => data.products.find((p) => p.key === pk)?.name || pk)
      .join(", ");
    ln(`| ${c.name} | ${productNames} | ${c.ehr} |`);
  }
  ln();
  ln("---");
  ln();

  // ── Flag Definitions ────────────────────────────────────────────────────────
  ln("## Flag Definitions");
  ln();

  const categoryLabels = buildCategoryLabels();

  for (const [catKey, catLabel] of Object.entries(categoryLabels)) {
    ln(`### ${catLabel}`);
    ln();
    ln("| Flag Key | Display Name | Type | Description |");
    ln("|----------|-------------|------|-------------|");
    for (const flag of data.flagDefinitions[catKey]) {
      ln(`| \`${flag.key}\` | ${flag.name} | boolean | ${flag.description} |`);
    }
    ln();
  }

  ln("---");
  ln();

  // ── Customer Configurations ─────────────────────────────────────────────────
  ln("## Customer Configurations");
  ln();

  for (const customer of data.customers) {
    ln(`### ${customer.name}`);
    ln();
    const productNames = customer.products
      .map((pk) => data.products.find((p) => p.key === pk)?.name || pk)
      .join(", ");
    ln(`**Products:** ${productNames} | **EHR:** ${customer.ehr}`);
    ln();

    for (const productKey of customer.products) {
      const product = data.products.find((p) => p.key === productKey);
      const productName = product ? product.name : productKey;
      const config = data.configurations[customer.key]?.[productKey];

      ln(`#### ${productName}`);
      ln();
      ln("| Feature | Enabled | Disabled | Notes |");
      ln("|---------|---------|----------|-------|");

      for (const [catKey, catLabel] of Object.entries(buildCategoryLabels())) {
        // Check if any flags in this category are applicable to this product
        const applicableFlags = (data.flagDefinitions[catKey] || []).filter((flag) =>
          isFlagApplicableToProduct(flag, productKey)
        );
        if (applicableFlags.length === 0) continue;

        ln(`| **${catLabel}** | | | |`);

        for (const flag of applicableFlags) {
          const value = config?.flags?.[flag.key];
          const note = config?.notes?.[flag.key] || "";
          let flagDisplayName = flag.name;

          // MedStar Cerner-specific naming
          if (customer.ehr === "Cerner" && flag.key === "nurse_writeback_flowsheet") {
            flagDisplayName = "Nurse Assessment - Auto Writeback to Flowsheet Rows (Cerner iCare)";
          }

          let enabledCol = "";
          let disabledCol = "";

          if (value === true) {
            enabledCol = "✓";
          } else if (value === false) {
            disabledCol = "✓";
          }

          // Special case: ThedaCare fluid_mod_ehr_order_set has both columns checked
          if (
            customer.key === "thedacare" &&
            flag.key === "fluid_mod_ehr_order_set" &&
            value === true
          ) {
            enabledCol = "✓";
            disabledCol = "✓";
          }

          // For Palliative Care / Deterioration, bundle_tracking is always false with a note
          if (
            (productKey === "palliative_care" || productKey === "deterioration") &&
            flag.key === "bundle_tracking" &&
            value === false
          ) {
            const defaultNote =
              productKey === "palliative_care"
                ? "Not applicable for Palliative Care"
                : "Not applicable for Deterioration";
            const finalNote = note || defaultNote;
            ln(`| ${flagDisplayName} | ${enabledCol} | ${disabledCol} | ${finalNote} |`);
            continue;
          }

          ln(`| ${flagDisplayName} | ${enabledCol} | ${disabledCol} | ${note} |`);
        }
      }

      ln();
    }

    ln("---");
    ln();
  }

  // ── Changelog ───────────────────────────────────────────────────────────────
  ln("## Changelog");
  ln();
  ln("| Date | Author | Change |");
  ln("|------|--------|--------|");
  for (const entry of data.changelog) {
    ln(`| ${entry.date} | ${entry.author} | ${entry.change} |`);
  }
  ln();

  return lines.join("\n");
}

function isFlagApplicableToProduct(flag, productKey) {
  if (flag.applicableProducts === "all") return true;
  return flag.applicableProducts.includes(productKey);
}

function buildCategoryLabels() {
  const labels = {};
  for (const catKey of Object.keys(data.flagDefinitions)) {
    // Convert snake_case key to Title Case label
    labels[catKey] = catKey
      .split("_")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" ");
  }
  return labels;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  HTML GENERATION
// ═══════════════════════════════════════════════════════════════════════════════

function generateHTML() {
  // Transform JSON data into the FLAG_DATA format the HTML JS expects
  const flagData = buildFlagDataForHTML();
  const flagDataJSON = JSON.stringify(flagData, null, 2);

  // Format the last-updated date for display
  const lastUpdated = formatDateDisplay(data.meta.lastUpdated);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Feature Flag Configuration Viewer</title>
<style>
${getCSS()}
</style>
</head>
<body>

<div class="header">
  <div class="header-inner">
    <div>
      <h1>Feature Flag Configuration</h1>
      <div class="header-subtitle">Clinical team configuration viewer</div>
    </div>
    <div class="header-right">
      <div class="search-box">
        <svg class="search-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
        <input type="text" id="searchInput" placeholder="Search flags...">
      </div>
      <span class="last-updated">Updated ${lastUpdated}</span>
    </div>
  </div>
</div>

<div class="main">
  <div class="stats-bar" id="statsBar"></div>

  <div class="filter-bar">
    <div class="filter-group">
      <label>Customer:</label>
      <div id="customerFilters"></div>
    </div>
    <div class="filter-divider"></div>
    <div class="filter-group">
      <label>Product:</label>
      <div id="productFilters"></div>
    </div>
    <div class="filter-divider"></div>
    <div class="filter-group">
      <label>Status:</label>
      <div id="statusFilters"></div>
    </div>
    <div class="filter-divider"></div>
    <div class="filter-group">
      <label>Category:</label>
      <div id="categoryFilters"></div>
    </div>
  </div>

  <div class="tabs">
    <div class="tab active" data-view="matrix">Overview</div>
    <div class="tab" data-view="product">By Product</div>
    <div class="tab" data-view="customer">By Customer</div>
  </div>

  <div class="legend">
    <span class="legend-label">Legend:</span>
    <span class="legend-item"><span class="pill pill-enabled"><span class="pill-dot"></span>Enabled</span></span>
    <span class="legend-item"><span class="pill pill-disabled"><span class="pill-dot"></span>Disabled</span></span>
    <span class="legend-item"><span class="pill pill-value">Value</span></span>
    <span class="legend-item"><span class="pill pill-na">N/A</span></span>
    <span class="legend-item"><span class="pill pill-not-live">Not Live</span></span>
  </div>

  <div id="matrixView"></div>
  <div id="productView" class="hidden"></div>
  <div id="customerView" class="hidden"></div>
</div>

<script>
// ===== DATA (auto-generated from data/feature-flags.json — do not edit) =====
const FLAG_DATA = ${flagDataJSON};

${getAppJS()}
</script>
</body>
</html>`;
}

/**
 * Transform the canonical JSON into the display-name keyed format that
 * the HTML application JS expects.
 */
function buildFlagDataForHTML() {
  // Products as display names
  const products = data.products.map((p) => p.name);

  // Customers: display name → array of product display names
  const customers = {};
  for (const c of data.customers) {
    customers[c.name] = c.products.map(
      (pk) => data.products.find((p) => p.key === pk)?.name || pk
    );
  }

  // Flags by category — use display-name products
  const flags = {};
  for (const [catKey, catFlags] of Object.entries(data.flagDefinitions)) {
    flags[catKey] = catFlags.map((f) => ({
      key: f.key,
      name: f.name,
      type: "boolean",
      products:
        f.applicableProducts === "all"
          ? "all"
          : f.applicableProducts.map(
              (pk) => data.products.find((p) => p.key === pk)?.name || pk
            ),
    }));
  }

  // Notes: display-name customer → display-name product → flagKey → note
  const notes = {};
  for (const customer of data.customers) {
    const customerConfig = data.configurations[customer.key];
    if (!customerConfig) continue;
    for (const productKey of Object.keys(customerConfig)) {
      const productNotes = customerConfig[productKey].notes;
      if (!productNotes || Object.keys(productNotes).length === 0) continue;
      const productName =
        data.products.find((p) => p.key === productKey)?.name || productKey;
      if (!notes[customer.name]) notes[customer.name] = {};
      notes[customer.name][productName] = productNotes;
    }
  }

  // Configurations: display-name customer → display-name product → flag values
  const configurations = {};
  for (const customer of data.customers) {
    const customerConfig = data.configurations[customer.key];
    if (!customerConfig) continue;
    configurations[customer.name] = {};
    for (const productKey of Object.keys(customerConfig)) {
      const productName =
        data.products.find((p) => p.key === productKey)?.name || productKey;
      configurations[customer.name][productName] = customerConfig[productKey].flags;
    }
  }

  return { products, customers, flags, notes, configurations };
}

function formatDateDisplay(dateStr) {
  const d = new Date(dateStr + "T00:00:00");
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  return `${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;
}

// ─── CSS (embedded in generated HTML) ─────────────────────────────────────────
function getCSS() {
  return `  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

  :root {
    --blue-50: #eff6ff;
    --blue-100: #dbeafe;
    --blue-500: #3b82f6;
    --blue-600: #2563eb;
    --blue-700: #1d4ed8;
    --blue-800: #1e40af;
    --blue-900: #1e3a5f;
    --green-50: #f0fdf4;
    --green-100: #dcfce7;
    --green-600: #16a34a;
    --green-700: #15803d;
    --red-50: #fef2f2;
    --red-100: #fee2e2;
    --red-600: #dc2626;
    --red-700: #b91c1c;
    --gray-50: #f9fafb;
    --gray-100: #f3f4f6;
    --gray-200: #e5e7eb;
    --gray-300: #d1d5db;
    --gray-400: #9ca3af;
    --gray-500: #6b7280;
    --gray-600: #4b5563;
    --gray-700: #374151;
    --gray-800: #1f2937;
    --gray-900: #111827;
    --amber-50: #fffbeb;
    --amber-100: #fef3c7;
    --amber-600: #d97706;
    --purple-50: #faf5ff;
    --purple-100: #f3e8ff;
    --purple-600: #9333ea;
    --teal-50: #f0fdfa;
    --teal-600: #0d9488;
    --orange-50: #fff7ed;
    --orange-600: #ea580c;
    --radius: 8px;
    --shadow-sm: 0 1px 2px rgba(0,0,0,0.05);
    --shadow: 0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06);
    --shadow-md: 0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.06);
    --shadow-lg: 0 10px 15px rgba(0,0,0,0.1), 0 4px 6px rgba(0,0,0,0.05);
  }

  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    background: var(--gray-50);
    color: var(--gray-800);
    line-height: 1.5;
    min-height: 100vh;
  }

  .header {
    background: linear-gradient(135deg, var(--blue-800), var(--blue-900));
    color: white;
    padding: 20px 32px;
    box-shadow: var(--shadow-md);
    position: sticky;
    top: 0;
    z-index: 100;
  }
  .header-inner {
    max-width: 1400px;
    margin: 0 auto;
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 16px;
  }
  .header h1 { font-size: 20px; font-weight: 600; letter-spacing: -0.3px; }
  .header-subtitle { font-size: 13px; opacity: 0.75; margin-top: 2px; }
  .header-right { display: flex; align-items: center; gap: 12px; }
  .last-updated { font-size: 12px; opacity: 0.6; }

  .search-box { position: relative; }
  .search-box input {
    padding: 8px 12px 8px 36px;
    border: 1px solid rgba(255,255,255,0.2);
    border-radius: var(--radius);
    background: rgba(255,255,255,0.1);
    color: white;
    font-size: 14px;
    width: 260px;
    outline: none;
    transition: all 0.2s;
  }
  .search-box input::placeholder { color: rgba(255,255,255,0.5); }
  .search-box input:focus { background: rgba(255,255,255,0.15); border-color: rgba(255,255,255,0.4); width: 320px; }
  .search-icon { position: absolute; left: 10px; top: 50%; transform: translateY(-50%); opacity: 0.5; }

  .main { max-width: 1400px; margin: 0 auto; padding: 24px 32px 48px; }

  .stats-bar { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 24px; }
  .stat-card { background: white; border-radius: var(--radius); padding: 16px 20px; box-shadow: var(--shadow-sm); border: 1px solid var(--gray-200); }
  .stat-card .stat-label { font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--gray-500); margin-bottom: 4px; }
  .stat-card .stat-value { font-size: 28px; font-weight: 700; color: var(--gray-900); }
  .stat-card .stat-detail { font-size: 12px; color: var(--gray-400); margin-top: 2px; }

  .filter-bar { display: flex; align-items: center; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; }
  .filter-bar label { font-size: 13px; font-weight: 600; color: var(--gray-600); }
  .filter-group { display: flex; align-items: center; gap: 6px; }
  .filter-chip {
    padding: 6px 14px; border-radius: 20px; font-size: 13px; font-weight: 500;
    border: 1px solid var(--gray-300); background: white; color: var(--gray-600);
    cursor: pointer; transition: all 0.15s; user-select: none;
  }
  .filter-chip:hover { border-color: var(--blue-500); color: var(--blue-600); }
  .filter-chip.active { background: var(--blue-600); color: white; border-color: var(--blue-600); }
  .filter-divider { width: 1px; height: 24px; background: var(--gray-300); margin: 0 4px; }

  .tabs { display: flex; gap: 0; margin-bottom: 24px; border-bottom: 2px solid var(--gray-200); }
  .tab {
    padding: 10px 20px; font-size: 14px; font-weight: 500; color: var(--gray-500);
    cursor: pointer; border-bottom: 2px solid transparent; margin-bottom: -2px;
    transition: all 0.15s; user-select: none;
  }
  .tab:hover { color: var(--gray-700); }
  .tab.active { color: var(--blue-600); border-bottom-color: var(--blue-600); }

  .matrix-container { overflow-x: auto; background: white; border-radius: var(--radius); box-shadow: var(--shadow); border: 1px solid var(--gray-200); }
  .matrix-table { width: 100%; border-collapse: collapse; font-size: 13px; }
  .matrix-table thead th {
    background: var(--gray-50); padding: 12px 16px; text-align: left; font-weight: 600;
    color: var(--gray-700); border-bottom: 2px solid var(--gray-200); white-space: nowrap;
  }

  .sticky-header-clone {
    position: fixed;
    top: 0;
    z-index: 90;
    background: var(--gray-50);
    box-shadow: var(--shadow-md);
    border-bottom: 2px solid var(--gray-200);
    overflow: hidden;
    pointer-events: none;
    display: none;
  }
  .sticky-header-clone table {
    border-collapse: collapse;
    font-size: 13px;
  }
  .sticky-header-clone th {
    background: var(--gray-50); padding: 12px 16px; text-align: left; font-weight: 600;
    color: var(--gray-700); white-space: nowrap;
  }
  .matrix-table thead th:first-child { min-width: 220px; }
  .matrix-table thead .col-header-customer { font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--gray-400); }
  .matrix-table thead .col-header-product { font-size: 13px; font-weight: 600; color: var(--gray-700); }
  .matrix-table tbody td { padding: 10px 16px; border-bottom: 1px solid var(--gray-100); vertical-align: middle; }
  .matrix-table tbody td:first-child { position: sticky; left: 0; background: white; z-index: 5; font-weight: 500; color: var(--gray-800); min-width: 220px; }
  .matrix-table tbody tr:hover td { background: var(--blue-50); }
  .matrix-table tbody tr:hover td:first-child { background: var(--blue-50); }
  .matrix-table .product-group-row { cursor: pointer; }
  .matrix-table .product-group-row:hover td { background: var(--blue-100) !important; }
  .matrix-table .product-group-row td {
    background: var(--blue-50) !important; font-weight: 700; font-size: 13px;
    color: var(--blue-800); padding: 10px 16px; border-bottom: 2px solid var(--blue-100);
    border-top: 2px solid var(--gray-200);
  }
  .matrix-table .product-group-row td .product-badge { margin-right: 8px; vertical-align: middle; }
  .matrix-table .product-group-row .toggle-arrow {
    display: inline-block; width: 16px; font-size: 10px; color: var(--gray-400);
    transition: transform 0.2s; margin-right: 4px; text-align: center;
  }
  .matrix-table .product-group-row.collapsed .toggle-arrow { transform: rotate(-90deg); }
  .matrix-table .product-child-row.collapsed-child { display: none; }
  .matrix-table .category-row td {
    background: var(--gray-50) !important; font-weight: 700; font-size: 11px;
    text-transform: uppercase; letter-spacing: 0.8px; color: var(--gray-500);
    padding: 8px 16px; border-bottom: 1px solid var(--gray-200);
  }

  .pill { display: inline-flex; align-items: center; gap: 5px; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: 500; white-space: nowrap; }
  .pill-enabled { background: var(--green-100); color: var(--green-700); }
  .pill-disabled { background: var(--red-100); color: var(--red-700); }
  .pill-na { background: var(--gray-100); color: var(--gray-400); font-style: italic; }
  .pill-not-live { background: var(--amber-50); color: var(--amber-600); font-style: italic; border: 1px dashed var(--amber-100); }
  .pill-value { background: var(--blue-100); color: var(--blue-700); }
  .pill-dot { width: 6px; height: 6px; border-radius: 50%; }
  .pill-enabled .pill-dot { background: var(--green-600); }
  .pill-disabled .pill-dot { background: var(--red-600); }

  .cards-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(420px, 1fr)); gap: 20px; }
  .customer-card { background: white; border-radius: var(--radius); box-shadow: var(--shadow); border: 1px solid var(--gray-200); overflow: hidden; transition: box-shadow 0.2s; }
  .customer-card:hover { box-shadow: var(--shadow-lg); }
  .card-header { padding: 16px 20px; border-bottom: 1px solid var(--gray-100); display: flex; align-items: center; justify-content: space-between; }
  .card-customer-name { font-size: 16px; font-weight: 700; color: var(--gray-900); }
  .card-product-badges { display: flex; gap: 6px; }
  .product-badge { padding: 3px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.3px; }
  .badge-sepsis { background: var(--red-50); color: var(--red-600); border: 1px solid var(--red-100); }
  .badge-palliative { background: var(--purple-50); color: var(--purple-600); border: 1px solid var(--purple-100); }
  .badge-deterioration { background: var(--amber-50); color: var(--amber-600); border: 1px solid var(--amber-100); }
  .card-body { padding: 0; }
  .card-product-section { border-bottom: 1px solid var(--gray-100); }
  .card-product-section:last-child { border-bottom: none; }
  .card-product-title { padding: 10px 20px; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; color: var(--gray-500); background: var(--gray-50); border-bottom: 1px solid var(--gray-100); }
  .flag-list { list-style: none; }
  .flag-item { display: flex; align-items: center; justify-content: space-between; padding: 8px 20px; border-bottom: 1px solid var(--gray-50); font-size: 13px; }
  .flag-item:last-child { border-bottom: none; }
  .flag-item:hover { background: var(--gray-50); }
  .flag-name { color: var(--gray-700); }
  .flag-category-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--gray-400); margin-left: 8px; }
  .card-footer { padding: 12px 20px; background: var(--gray-50); border-top: 1px solid var(--gray-100); display: flex; justify-content: space-between; font-size: 12px; color: var(--gray-500); }

  .product-section { margin-bottom: 32px; }
  .product-section-header { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }
  .product-section-title { font-size: 18px; font-weight: 700; color: var(--gray-900); }
  .product-customer-count { font-size: 13px; color: var(--gray-500); }
  .product-table-container { background: white; border-radius: var(--radius); box-shadow: var(--shadow); border: 1px solid var(--gray-200); overflow-x: auto; }
  .product-table { width: 100%; border-collapse: collapse; font-size: 13px; }
  .product-table thead th { background: var(--gray-50); padding: 12px 16px; text-align: left; font-weight: 600; color: var(--gray-700); border-bottom: 2px solid var(--gray-200); white-space: nowrap; }
  .product-table tbody td { padding: 10px 16px; border-bottom: 1px solid var(--gray-100); }
  .product-table tbody tr:hover td { background: var(--blue-50); }
  .product-table .category-row td { background: var(--gray-50) !important; font-weight: 700; font-size: 11px; text-transform: uppercase; letter-spacing: 0.8px; color: var(--gray-500); padding: 8px 16px; }

  .no-results { text-align: center; padding: 48px 24px; color: var(--gray-400); }
  .no-results-icon { font-size: 48px; margin-bottom: 12px; display: block; }
  .no-results-text { font-size: 16px; font-weight: 500; }
  .no-results-sub { font-size: 13px; margin-top: 4px; }

  @media (max-width: 768px) {
    .header { padding: 16px; }
    .main { padding: 16px; }
    .cards-grid { grid-template-columns: 1fr; }
    .search-box input { width: 180px; }
    .search-box input:focus { width: 220px; }
    .stats-bar { grid-template-columns: repeat(2, 1fr); }
    .filter-bar { gap: 8px; }
  }

  .hidden { display: none !important; }

  .has-note { position: relative; cursor: help; }
  .has-note::after { content: "*"; color: var(--amber-600); font-weight: 700; margin-left: 4px; font-size: 14px; }
  .note-text { display: block; font-size: 11px; color: var(--gray-400); margin-top: 2px; font-style: italic; line-height: 1.3; }

  .legend { display: flex; gap: 16px; align-items: center; margin-bottom: 16px; flex-wrap: wrap; }
  .legend-label { font-size: 12px; color: var(--gray-500); font-weight: 600; }
  .legend-item { display: flex; align-items: center; gap: 6px; font-size: 12px; color: var(--gray-600); }`;
}

// ─── Application JS (embedded in generated HTML) ─────────────────────────────
function getAppJS() {
  return `// ===== STATE =====
const state = {
  view: "matrix",
  search: "",
  customerFilter: "all",
  productFilter: "all",
  statusFilter: "all",
  categoryFilter: "all",
  collapsedProducts: {}
};

// ===== HELPERS =====
function getAllFlags() {
  const all = [];
  for (const [catKey, catFlags] of Object.entries(FLAG_DATA.flags)) {
    for (const f of catFlags) {
      all.push({ ...f, category: catKey });
    }
  }
  return all;
}

function getFlagNote(customer, product, flagKey) {
  return FLAG_DATA.notes?.[customer]?.[product]?.[flagKey] || "";
}

function getCustomerProductPairs() {
  const pairs = [];
  for (const [customer, products] of Object.entries(FLAG_DATA.customers)) {
    for (const product of products) {
      pairs.push({ customer, product });
    }
  }
  return pairs;
}

function isFlagApplicable(flag, product) {
  return flag.products === "all" || flag.products.includes(product);
}

function getFlagValue(customer, product, flagKey) {
  const config = FLAG_DATA.configurations[customer]?.[product];
  if (!config) return undefined;
  return config[flagKey];
}

function renderPill(value, flag, applicable, notLive) {
  if (notLive) return '<span class="pill pill-not-live">Not Live</span>';
  if (!applicable) return '<span class="pill pill-na">N/A</span>';
  if (value === undefined) return '<span class="pill pill-na">N/A</span>';
  if (typeof value === "string") return \`<span class="pill pill-value">\${value}</span>\`;
  if (value === true) return '<span class="pill pill-enabled"><span class="pill-dot"></span>Enabled</span>';
  return '<span class="pill pill-disabled"><span class="pill-dot"></span>Disabled</span>';
}

function productBadgeClass(product) {
  if (product === "Sepsis") return "badge-sepsis";
  if (product === "Palliative Care") return "badge-palliative";
  if (product === "Deterioration") return "badge-deterioration";
  return "";
}

function matchesSearch(flagName) {
  if (!state.search) return true;
  return flagName.toLowerCase().includes(state.search.toLowerCase());
}

function matchesFilters(customer, product, flag, value) {
  if (state.customerFilter !== "all" && customer !== state.customerFilter) return false;
  if (state.productFilter !== "all" && product !== state.productFilter) return false;
  if (state.categoryFilter !== "all" && flag.category !== state.categoryFilter) return false;
  if (state.statusFilter !== "all") {
    if (state.statusFilter === "enabled" && value !== true && typeof value !== "string") return false;
    if (state.statusFilter === "disabled" && value !== false) return false;
  }
  return true;
}

// ===== STATS =====
function renderStats() {
  const pairs = getCustomerProductPairs();
  const allFlags = getAllFlags();
  let totalEnabled = 0, totalDisabled = 0, totalFlags = 0;
  for (const { customer, product } of pairs) {
    for (const flag of allFlags) {
      if (!isFlagApplicable(flag, product)) continue;
      totalFlags++;
      const val = getFlagValue(customer, product, flag.key);
      if (val === true || typeof val === "string") totalEnabled++;
      else totalDisabled++;
    }
  }
  document.getElementById("statsBar").innerHTML = \`
    <div class="stat-card">
      <div class="stat-label">Customers</div>
      <div class="stat-value">\${Object.keys(FLAG_DATA.customers).length}</div>
      <div class="stat-detail">\${pairs.length} customer-product configs</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Products</div>
      <div class="stat-value">\${FLAG_DATA.products.length}</div>
      <div class="stat-detail">\${FLAG_DATA.products.join(", ")}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Flags Defined</div>
      <div class="stat-value">\${allFlags.length}</div>
      <div class="stat-detail">\${Object.entries(FLAG_DATA.flags).map(([k, v]) => v.length + ' ' + k.replace(/_/g, ' ')).join(', ')}</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Enabled / Disabled</div>
      <div class="stat-value" style="color:var(--green-600)">\${totalEnabled} <span style="color:var(--gray-300)">/</span> <span style="color:var(--red-600)">\${totalDisabled}</span></div>
      <div class="stat-detail">\${Math.round(totalEnabled / totalFlags * 100)}% enabled across all configs</div>
    </div>
  \`;
}

// ===== FILTERS =====
function renderFilters() {
  const customers = Object.keys(FLAG_DATA.customers);
  const products = FLAG_DATA.products;

  document.getElementById("customerFilters").innerHTML =
    \`<span class="filter-chip \${state.customerFilter === 'all' ? 'active' : ''}" data-filter="customer" data-value="all">All</span>\` +
    customers.map(c => \`<span class="filter-chip \${state.customerFilter === c ? 'active' : ''}" data-filter="customer" data-value="\${c}">\${c}</span>\`).join("");

  document.getElementById("productFilters").innerHTML =
    \`<span class="filter-chip \${state.productFilter === 'all' ? 'active' : ''}" data-filter="product" data-value="all">All</span>\` +
    products.map(p => \`<span class="filter-chip \${state.productFilter === p ? 'active' : ''}" data-filter="product" data-value="\${p}">\${p}</span>\`).join("");

  document.getElementById("statusFilters").innerHTML =
    \`<span class="filter-chip \${state.statusFilter === 'all' ? 'active' : ''}" data-filter="status" data-value="all">All</span>\` +
    \`<span class="filter-chip \${state.statusFilter === 'enabled' ? 'active' : ''}" data-filter="status" data-value="enabled">Enabled</span>\` +
    \`<span class="filter-chip \${state.statusFilter === 'disabled' ? 'active' : ''}" data-filter="status" data-value="disabled">Disabled</span>\`;

  document.getElementById("categoryFilters").innerHTML =
    \`<span class="filter-chip \${state.categoryFilter === 'all' ? 'active' : ''}" data-filter="category" data-value="all">All</span>\` +
    Object.keys(FLAG_DATA.flags).map(k => \`<span class="filter-chip \${state.categoryFilter === k ? 'active' : ''}" data-filter="category" data-value="\${k}">\${k.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')}</span>\`).join("");
}

// ===== CUSTOMER VIEW =====
function renderCustomerView() {
  const customers = Object.entries(FLAG_DATA.customers).filter(([c]) =>
    state.customerFilter === "all" || state.customerFilter === c
  );
  const allFlags = getAllFlags();

  if (customers.length === 0) {
    document.getElementById("customerView").innerHTML = \`<div class="no-results"><span class="no-results-icon">&#128269;</span><div class="no-results-text">No customers match filters</div></div>\`;
    return;
  }

  let html = '<div class="cards-grid">';
  for (const [customer, products] of customers) {
    const filteredProducts = products.filter(p => state.productFilter === "all" || state.productFilter === p);
    if (filteredProducts.length === 0) continue;

    let enabledCount = 0, disabledCount = 0;
    html += \`<div class="customer-card"><div class="card-header"><span class="card-customer-name">\${customer}</span><div class="card-product-badges">\`;
    for (const p of filteredProducts) {
      html += \`<span class="product-badge \${productBadgeClass(p)}">\${p}</span>\`;
    }
    html += '</div></div><div class="card-body">';

    for (const product of filteredProducts) {
      html += \`<div class="card-product-section">\`;
      if (filteredProducts.length > 1) {
        html += \`<div class="card-product-title">\${product}</div>\`;
      }
      html += '<ul class="flag-list">';
      const categories = Object.keys(FLAG_DATA.flags).map(k => ({ key: k, label: k.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') }));
      for (const cat of categories) {
        if (state.categoryFilter !== "all" && state.categoryFilter !== cat.key) continue;
        const catFlags = allFlags.filter(f => f.category === cat.key && isFlagApplicable(f, product));
        for (const flag of catFlags) {
          if (!matchesSearch(flag.name)) continue;
          const val = getFlagValue(customer, product, flag.key);
          if (state.statusFilter === "enabled" && val !== true && typeof val !== "string") continue;
          if (state.statusFilter === "disabled" && val !== false) continue;
          if (val === true || typeof val === "string") enabledCount++; else disabledCount++;
          const note = getFlagNote(customer, product, flag.key);
          html += \`<li class="flag-item"><span class="flag-name">\${flag.name}<span class="flag-category-label">\${cat.label}</span>\${note ? '<span class="note-text">' + note + '</span>' : ''}</span>\${renderPill(val, flag, true)}</li>\`;
        }
      }
      html += '</ul></div>';
    }

    html += \`</div><div class="card-footer"><span>\${enabledCount} enabled</span><span>\${disabledCount} disabled</span></div></div>\`;
  }
  html += '</div>';
  document.getElementById("customerView").innerHTML = html;
}

// ===== PRODUCT VIEW =====
function renderProductView() {
  const products = FLAG_DATA.products.filter(p => state.productFilter === "all" || state.productFilter === p);
  const allFlags = getAllFlags();

  if (products.length === 0) {
    document.getElementById("productView").innerHTML = \`<div class="no-results"><span class="no-results-icon">&#128269;</span><div class="no-results-text">No products match filters</div></div>\`;
    return;
  }

  let html = '';
  for (const product of products) {
    const customersWithProduct = Object.entries(FLAG_DATA.customers)
      .filter(([c, prods]) => prods.includes(product) && (state.customerFilter === "all" || state.customerFilter === c))
      .map(([c]) => c);
    if (customersWithProduct.length === 0) continue;

    html += \`<div class="product-section"><div class="product-section-header"><span class="product-badge \${productBadgeClass(product)}" style="font-size:13px;padding:5px 14px;">\${product}</span><span class="product-section-title"></span><span class="product-customer-count">\${customersWithProduct.length} customer\${customersWithProduct.length > 1 ? 's' : ''}</span></div>\`;
    html += '<div class="product-table-container"><table class="product-table"><thead><tr><th>Feature Flag</th>';
    for (const c of customersWithProduct) {
      html += \`<th>\${c}</th>\`;
    }
    html += '</tr></thead><tbody>';

    const categories = Object.keys(FLAG_DATA.flags).map(k => ({ key: k, label: k.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') }));
    for (const cat of categories) {
      if (state.categoryFilter !== "all" && state.categoryFilter !== cat.key) continue;
      const catFlags = allFlags.filter(f => f.category === cat.key && isFlagApplicable(f, product));
      const visibleFlags = catFlags.filter(f => {
        if (!matchesSearch(f.name)) return false;
        if (state.statusFilter !== "all") {
          const anyMatch = customersWithProduct.some(c => {
            const val = getFlagValue(c, product, f.key);
            if (state.statusFilter === "enabled") return val === true || typeof val === "string";
            if (state.statusFilter === "disabled") return val === false;
            return true;
          });
          if (!anyMatch) return false;
        }
        return true;
      });
      if (visibleFlags.length === 0) continue;
      html += \`<tr class="category-row"><td colspan="\${customersWithProduct.length + 1}">\${cat.label}</td></tr>\`;
      for (const flag of visibleFlags) {
        html += \`<tr><td style="font-weight:500">\${flag.name}</td>\`;
        for (const c of customersWithProduct) {
          const val = getFlagValue(c, product, flag.key);
          const note = getFlagNote(c, product, flag.key);
          html += \`<td>\${renderPill(val, flag, true)}\${note ? '<span class="note-text">' + note + '</span>' : ''}</td>\`;
        }
        html += '</tr>';
      }
    }

    html += '</tbody></table></div></div>';
  }
  document.getElementById("productView").innerHTML = html || \`<div class="no-results"><span class="no-results-icon">&#128269;</span><div class="no-results-text">No flags match your search</div></div>\`;
}

// ===== MATRIX VIEW =====
function renderMatrixView() {
  const allCustomers = Object.keys(FLAG_DATA.customers);
  const allProducts = FLAG_DATA.products;
  const allFlags = getAllFlags();

  // Filter customers
  const customers = allCustomers.filter(c => state.customerFilter === "all" || state.customerFilter === c);
  if (customers.length === 0) {
    document.getElementById("matrixView").innerHTML = \`<div class="no-results"><span class="no-results-icon">&#128269;</span><div class="no-results-text">No customers match filters</div></div>\`;
    return;
  }

  // Filter products
  const products = allProducts.filter(p => state.productFilter === "all" || state.productFilter === p);
  if (products.length === 0) {
    document.getElementById("matrixView").innerHTML = \`<div class="no-results"><span class="no-results-icon">&#128269;</span><div class="no-results-text">No products match filters</div></div>\`;
    return;
  }

  // Columns = one per customer
  let html = '<div class="matrix-container"><table class="matrix-table"><thead>';
  html += '<tr><th>Feature Flag</th>';
  for (const customer of customers) {
    html += \`<th style="text-align:center;border-left:2px solid var(--gray-200)"><span class="col-header-customer">\${customer}</span></th>\`;
  }
  html += '</tr></thead><tbody>';

  const categories = Object.keys(FLAG_DATA.flags).map(k => ({ key: k, label: k.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ') }));

  let hasVisibleRows = false;

  // Rows grouped by Product → Category → Flag
  for (const product of products) {
    const pgKey = product.replace(/\\s+/g, '_');
    const isCollapsed = state.collapsedProducts && state.collapsedProducts[product];
    const childClass = 'product-child-row' + (isCollapsed ? ' collapsed-child' : '');

    // Collect all visible flags for this product
    let productHasFlags = false;
    let productRowsHtml = '';

    for (const cat of categories) {
      if (state.categoryFilter !== "all" && state.categoryFilter !== cat.key) continue;
      const catFlags = allFlags.filter(f => f.category === cat.key && isFlagApplicable(f, product));

      // Filter by search and status
      const visibleFlags = catFlags.filter(f => {
        if (!matchesSearch(f.name)) return false;
        if (state.statusFilter !== "all") {
          const anyMatch = customers.some(c => {
            if (!FLAG_DATA.customers[c].includes(product)) return false;
            const val = getFlagValue(c, product, f.key);
            if (state.statusFilter === "enabled") return val === true || typeof val === "string";
            if (state.statusFilter === "disabled") return val === false;
            return true;
          });
          if (!anyMatch) return false;
        }
        return true;
      });

      if (visibleFlags.length === 0) continue;
      productHasFlags = true;

      productRowsHtml += \`<tr class="category-row \${childClass}" data-product-group="\${pgKey}"><td colspan="\${customers.length + 1}">\${cat.label}</td></tr>\`;

      for (const flag of visibleFlags) {
        productRowsHtml += \`<tr class="\${childClass}" data-product-group="\${pgKey}"><td style="font-weight:500">\${flag.name}</td>\`;
        for (const customer of customers) {
          const isNotLive = !FLAG_DATA.customers[customer].includes(product);
          const val = isNotLive ? undefined : getFlagValue(customer, product, flag.key);
          const note = isNotLive ? "" : getFlagNote(customer, product, flag.key);
          productRowsHtml += \`<td style="text-align:center;border-left:1px solid var(--gray-100)">\${renderPill(val, flag, true, isNotLive)}\${note ? '<span class="note-text">' + note + '</span>' : ''}</td>\`;
        }
        productRowsHtml += '</tr>';
      }
    }

    if (productHasFlags) {
      hasVisibleRows = true;
      // Product group header row
      html += \`<tr class="product-group-row\${isCollapsed ? ' collapsed' : ''}" data-product-toggle="\${pgKey}"><td colspan="\${customers.length + 1}"><span class="toggle-arrow">\u25BC</span><span class="product-badge \${productBadgeClass(product)}">\${product}</span></td></tr>\`;
      html += productRowsHtml;
    }
  }

  if (!hasVisibleRows) {
    html += \`<tr><td colspan="\${customers.length + 1}" style="text-align:center;padding:32px;color:var(--gray-400)">No flags match your search</td></tr>\`;
  }

  html += '</tbody></table></div>';
  document.getElementById("matrixView").innerHTML = html;
}

// ===== RENDER =====
function render() {
  renderStats();
  renderFilters();

  document.getElementById("matrixView").classList.toggle("hidden", state.view !== "matrix");
  document.getElementById("productView").classList.toggle("hidden", state.view !== "product");
  document.getElementById("customerView").classList.toggle("hidden", state.view !== "customer");

  if (state.view === "matrix") renderMatrixView();
  else if (state.view === "product") renderProductView();
  else if (state.view === "customer") renderCustomerView();
}

// ===== EVENTS =====
document.addEventListener("click", (e) => {
  if (e.target.classList.contains("tab")) {
    document.querySelectorAll(".tab").forEach(t => t.classList.remove("active"));
    e.target.classList.add("active");
    state.view = e.target.dataset.view;
    render();
  }
  if (e.target.classList.contains("filter-chip")) {
    const filter = e.target.dataset.filter;
    const value = e.target.dataset.value;
    if (filter === "customer") state.customerFilter = value;
    if (filter === "product") state.productFilter = value;
    if (filter === "status") state.statusFilter = value;
    if (filter === "category") state.categoryFilter = value;
    render();
  }

  // Product group collapse/expand
  const pgRow = e.target.closest(".product-group-row");
  if (pgRow) {
    const pgKey = pgRow.dataset.productToggle;
    const isCollapsed = pgRow.classList.toggle("collapsed");
    // Find product name from the badge text
    const badge = pgRow.querySelector(".product-badge");
    if (badge) state.collapsedProducts[badge.textContent] = isCollapsed;
    // Toggle child rows via DOM
    document.querySelectorAll(\`.product-child-row[data-product-group="\${pgKey}"]\`).forEach(row => {
      row.classList.toggle("collapsed-child", isCollapsed);
    });
  }
});

document.getElementById("searchInput").addEventListener("input", (e) => {
  state.search = e.target.value;
  render();
});

// ===== STICKY HEADER CLONE =====
let stickyClone = null;

function setupStickyHeader() {
  // Remove old clone if any
  if (stickyClone) { stickyClone.remove(); stickyClone = null; }

  const container = document.querySelector(".matrix-container");
  const table = document.querySelector(".matrix-table");
  if (!container || !table) return;
  const thead = table.querySelector("thead");
  if (!thead) return;

  // Create fixed clone container
  stickyClone = document.createElement("div");
  stickyClone.className = "sticky-header-clone";
  document.body.appendChild(stickyClone);

  function syncClone() {
    if (!document.querySelector(".matrix-table")) { stickyClone.style.display = "none"; return; }

    const headerBar = document.querySelector(".header");
    const headerBottom = headerBar ? headerBar.getBoundingClientRect().bottom : 0;
    const containerRect = container.getBoundingClientRect();
    const theadRect = thead.getBoundingClientRect();

    // Show clone when the original thead is scrolled above the header bar
    // but the table is still partially visible
    const shouldShow = theadRect.top < headerBottom && containerRect.bottom > headerBottom + 60;

    if (!shouldShow) { stickyClone.style.display = "none"; return; }

    stickyClone.style.display = "block";
    stickyClone.style.top = headerBottom + "px";
    stickyClone.style.left = containerRect.left + "px";
    stickyClone.style.width = containerRect.width + "px";

    // Clone the thead with current column widths
    const ths = thead.querySelectorAll("th");
    let cloneHTML = '<table><thead><tr>';
    ths.forEach(th => {
      const w = th.getBoundingClientRect().width;
      cloneHTML += '<th style="min-width:' + w + 'px;max-width:' + w + 'px;text-align:' + getComputedStyle(th).textAlign + ';border-left:' + getComputedStyle(th).borderLeft + '">' + th.innerHTML + '</th>';
    });
    cloneHTML += '</tr></thead></table>';
    stickyClone.innerHTML = cloneHTML;

    // Sync horizontal scroll
    stickyClone.scrollLeft = container.scrollLeft;
  }

  window.addEventListener("scroll", syncClone, { passive: true });
  container.addEventListener("scroll", () => { if (stickyClone) stickyClone.scrollLeft = container.scrollLeft; }, { passive: true });
  window.addEventListener("resize", syncClone, { passive: true });

  // Store cleanup references
  stickyClone._cleanup = () => {
    window.removeEventListener("scroll", syncClone);
    window.removeEventListener("resize", syncClone);
  };
}

// Re-setup sticky header after each render
const _origRender = render;
render = function() { _origRender(); if (state.view === "matrix") setTimeout(setupStickyHeader, 0); else if (stickyClone) stickyClone.style.display = "none"; };

// Initial render
render();`;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  MAIN
// ═══════════════════════════════════════════════════════════════════════════════

function main() {
  console.log("Reading data/feature-flags.json ...");

  // Generate markdown
  const md = generateMarkdown();
  fs.writeFileSync(MD_PATH, md, "utf-8");
  console.log(`✓ Generated feature-flags.md  (${md.length.toLocaleString()} chars)`);

  // Generate HTML
  const html = generateHTML();
  fs.writeFileSync(HTML_PATH, html, "utf-8");
  console.log(`✓ Generated index.html        (${html.length.toLocaleString()} chars)`);

  console.log("\nDone! Both files are up to date with data/feature-flags.json.");
}

main();
